export const categories=[
    {
        id:"01",
        category:"Breakfast",
    },
    {
        id:"02",
        category:"Lunch",
    },
    {
        id:"03",
        category:"Dinner",
    }
];

export const recipeList=[
    {
        id:"01",
        name: "Chicken Adobo",
        color:"#904430",
        image: require("./screens/assets/adobo.jpg"),
        ingredients: ["Chicken Thighs","Sugar","Soy sauce","Vinegar","Bay Leaves","Onion","Garlic","Oil","Green Onion","Red Chilies"],
        calories:"654 kcal",
        time:"1hr 15 mins",
        steps: [
            "In a large bowl, combine the soy sauce, vinegar, brown sugar, half of the garlic and the bay leaves. Add the chicken thighs and toss well. Marinate for 20 minutes to overnight",
            "In a large skillet, with a lid, heat 2 tbsp of the vegetable oil. Remove the chicken from the marinade, reserving the marinade, and cook about 4 minutes per side on high heat or until golden brown. Transfer the cooked chicken to a plate.",
            "Add the remaining 1 tbsp of oil to the skillet over medium-high heat. Add the onion and cook until the onion has softened and has begun to caramelize, about 5 minutes. If wanting to spice this up, now is the time to add some red chilies. Stir in the remaining garlic and cook for another minute until aromatic.",
            "Add the chicken pieces back to the skillet right over the onion, pour the reserved marinade over the chicken and about ¼ cup of water. Bring to a boil, then reduce the heat to low, cover the skillet and simmer for 20 to 30 minutes. Remove the lid from the skillet and increase the heat to medium-high. Cook for another 5 to 10 minutes, or until the sauce has started to reduce, thicken slightly and become glossy.",
            "Serve garnished with green onion and red chilies.",
        ],
    },
    {
        id:"02",
        name: "Chopsuey",
        color:"#5d7c2c",
        image: require("./screens/assets/chopsuey.jpg"),
        ingredients: ["Chicken Thighs","Quail Eggs","Cornstarch","Soy sauce","Egg White","Garlic","Onion","Oil","Cauliflower","Snow peas","Cabbage","Red Bell pepper","Carrots","Fish sauce","Chicken broth","Salt","Pepper"],
        calories:"170 kcal",
        time:"35 mins",
        steps: [
            "In a bowl, combine the chicken strips, 1 teaspoon cornstarch, soy sauce and egg white.",
            "Mix well and marinate for 30 minutes.",
            "Heat oil in a wok or sauté pan over medium high heat.",
            "Add garlic and onion; sauté until onion is soft and wilted.",
            "Add chicken strips and cook until meat is browned and no longer pink",
            "Add all the vegetable and fish sauce.",
            "Stir to combine and then add the broth.",
            "Bring to a boil, cover and let simmer for 5 minutes or until vegetables are crisp tender.",
            "Stir the Cornstarch Mixture and add put in the Pan.",
            "Let mixture simmer until sauce thickens.",
            "Add Salt and Pepper to taste. Adjust according to taste.",
            "Serve and Enjoy!",
        ],
    },
    {
        id:"03",
        name: "Pandesal",
        color:"#c79b61",
        image: require("./screens/assets/pandesal.jpg"),
        ingredients: ["Milk","Yeast","Bread flour","Sugar","Salt","Butter","Bread crumbs"],
        calories:"73 kcal",
        time:"1hr 30 mins",
        steps: [
            "Combine all of the dough ingredients into a bowl of a stand mixer, including the yeast and softened vegan butter. Knead with the dough hook attachment on medium-low speed for 10 minutes until it forms one cohesive dough. You’ll know when your dough is fully kneaded when it springs back when you lightly press down on it.",
            "Shape the dough into a ball and transfer to a lightly oiled bowl and cover. Let the dough rise in a warm spot for 1 hour, or until doubled in size.",
            "While you wait, prepare a sheet pan by lining it with parchment paper (you can use a square pan if you don’t have a sheet pan as an option).",
            "Remove the dough from the bowl, and form it into a nice round ball. Place it in a lightly greased bowl, cover with a damp cloth, and set it aside in a warm spot for 1 hour to rise.",
            "When your dough is done rising, punch down the dough and measure out 9 equally sized pieces. You can eyeball this, or use a food scale for a more accurate amount.",
            "Shape each piece of dough into tight round balls. Roll the tops of each dough ball with breadcrumbs, and place them on the prepared pan. If you are using a sheet pan, leave about 1-2 inch of space in between. Cover with a damp cloth and allow them to rise for 30 minutes.",
            "While you wait for the rolls to rise, preheat the oven to 350° Fahrenheit. Remove the cloth and bake for 20-25 minutes or until fragrant and golden brown. Eat rolls warm or at room temp, and enjoy!",
        ],
    },
    {
        id:"04",
        name: "Tapsilog",
        color:"#6d3d1a",
        image: require("./screens/assets/tapsilog.jpg"),
        ingredients: ["Beef","Soy sauce","Lemon juice","Sugar","Garlic","Oil","Pepper"],
        calories:"226 kcal",
        time:"2hr 40 mins",
        steps: [
            "Using a sharp knife, thinly slice the meat across the grain.",
            "In a mixing bowl, combine soy sauce, lemon juice, brown sugar, minced garlic, and black pepper. Mix until the sugar is dissolved.",
            "Add the sliced beef into the marinade and make sure the beef is coated into the marinade. Marinate the meat for at least 2 hours in the refrigerator.",
            "When ready to fry, squeeze the meat to get rid of as much marinade as you can.",
            "Heat a frying pan over medium heat. Once heated, pour enough cooking oil to fry the beef tapa. Fry the meat in single layers, be sure not to overcrowd the pan. Sear the beef for 2-3 minutes on each side or until it's browned and slightly caramelized.",
            "Serve with fried rice and fried egg. Enjoy!",
        ],
    },
    {
        id:"05",
        name: "Pinakbet",
        color:"#c47519",
        image: require("./screens/assets/pinakbet.jpg"),
        ingredients: ["Oil","Water","Pork","Onion","Garlic","Bagoong alamang","Tomato sauce","Squash","Sitaw","Okra","Ampalaya"],
        calories:"184 kcal",
        time:"40 mins",
        steps: [
            "In a pot, combine oil, water, and pork. Cover and simmer until the fat comes out. Then sauté the pork until brown and crispy.",
            "Add the onion and sauté until translucent. Add the garlic and sauté until aromatic. Add bagoong and sauté for 1 minute.",
            "Add the Tomato Sauce, water, and squash. Simmer until squash is cooked.",
            "Add the sitaw, okra, and ampalaya then let it simmer for 2 minutes. Serve.",
        ],
    },
    {
        id:"06",
        name: "Tortang talong",
        color:"#a163b6",
        image: require("./screens/assets/tortangtalong.jpg"),
        ingredients: ["Eggplant","Egg","Salt","Pepper","Oil"],
        calories:"193 kcal",
        time:"30 mins",
        steps: [
            "Pierce the eggplants (in a few spots) with a fork/paring knife and arrange on a baking sheet (give at least an inch space in between).",
            "Position the oven rack at the second slot from the top. Turn the broiler on to HIGH and place the pan in the oven. Broil for 10 to 15 minutes or until soft and skins are starting to char. Remove from the oven and cool a bit then peel the skins off.",
            "In a small bowl, beat an egg (or use 2 for each eggplant, if you prefer) with a tiny pinch of salt . Place an eggplant on a plate and flatten with a fork then season with a pinch of salt and pepper. Pour the egg over the eggplant and lift to make sure all sides are well coated.",
            "Heat 3 tablespoons of oil in a nonstick frying pan (medium heat). Once hot, slide the eggplant-egg mixture and cook until golden and crisp on both sides. Repeat with the rest of the eggplants. You may need to add more oil after each batch.",
            "Serve with either ketchup or lemon-soy sauce and a bowl of hot steamed rice.",
        ],
    },
    
];